name: TSA Pipeline

on:
  push:
    branches:
      - main
      - 'release/*'
      - 'feature/*'
      - 'hotfix/*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'

  workflow_dispatch: # manual trigger

permissions:
  contents: write

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets:
      SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
  
  update-badges:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/update-badges.yml
    needs: tests

  build:
    name: Build & Release TSA
    needs: tests
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      # == Mac ==
      - name: Build app for mac
        if: runner.os == 'macOS'
        run: pyinstaller tsa_mac.spec
      
      - name: Create DMG and SHA256
        if: runner.os == 'macOS'
        run: |
          brew install create-dmg
          create-dmg \
            --volname "TSA" \
            --volicon "data/tsa_icon.icns" \
            --window-pos 200 120 \
            --window-size 500 300 \
            --icon-size 100 \
            --icon "TSA.app" 100 100 \
            --app-drop-link 375 100 \
            dist/TSA.dmg \
            dist/TSA.app
          shasum -a 256 dist/TSA.dmg > dist/TSA.dmg.sha256
      
      # == Linux ==
      - name: Build app for Linux
        if: runner.os == 'Linux'
        run: pyinstaller tsa_linux.spec

      - name: Install AppImage tool (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libfuse2
          wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-aarch64.AppImage -O appimagetool
          chmod +x appimagetool

      - name: Create AppDir and populate it
        if: runner.os == 'Linux'
        run: |
          mkdir -p TSA.AppDir/usr/bin
          cp -r dist/TSA/* TSA.AppDir/usr/bin/
          chmod +x TSA.AppDir/usr/bin/TSA
          ln -sf ./usr/bin/TSA TSA.AppDir/AppRun
          cat <<EOF > TSA.AppDir/tsa.desktop
          [Desktop Entry]
          Name=TSA
          Exec=TSA
          Icon=tsa_icon
          Type=Application
          Categories=Utility;
          EOF
          cp data/tsa_icon.png TSA.AppDir/tsa_icon.png

      - name: Build Linux AppImage
        if: runner.os == 'Linux'
        run: |
          ./appimagetool TSA.AppDir dist/TSA.AppImage
      
      - name: Create Linux archive and SHA256
        if: runner.os == 'Linux'
        run: |
          sha256sum dist/TSA.AppImage > dist/TSA.AppImage.sha256
  
      # == Windows ==
      - name: Build app for Windows
        if: runner.os == 'Windows'
        run: pyinstaller tsa_win.spec

      - name: Generate tsa.iss from template
        if: runner.os == 'Windows'
        shell: bash
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          sed "s/@VERSION@/$VERSION/" tsa.iss.in > tsa.iss

      - name: Install Inno Setup
        if: runner.os == 'Windows'
        run: choco install innosetup --yes

      - name: Compile Inno Setup installer
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          iscc tsa.iss
          mv TSASetup.exe dist/TSA-Win.exe

      - name: Create SHA256 for Windows installer
        if: runner.os == 'Windows'
        shell: pwsh
        run: CertUtil -hashfile dist/TSA-Win.exe SHA256 > dist/TSA-Win.sha256

      # == Upload Release ==
      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/TSA.dmg
            dist/TSA.dmg.sha256
            dist/TSA-Win.exe
            dist/TSA-Win.sha256
            dist/TSA.AppImage
            dist/TSA.AppImage.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}