name: Tests

on:
  workflow_call:
    # secrets:
    #   SAFETY_API_KEY:
    #     required: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Update and Install system packages for PyQt6
        run: |
          sudo apt-get update && sudo apt-get install -y \
            libxkbcommon-x11-0 libxcb-cursor0 \
            libegl1 libgl1 libglib2.0-0 libx11-xcb1 libxcb-glx0 libdbus-1-3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black pylint bandit pip-audit

      - name: Run Unit Tests
        run: |
          mkdir -p badges
          PYTHONPATH=. pytest -s tests | tee badges/unit-tests.txt
          echo '{"label": "Unit Tests", "message": "Passed", "color": "green"}' > badges/unit-tests.json
        continue-on-error: true

      - name: Record Unit Test Failure
        if: failure()
        run: |
          echo '{"label": "Unit Tests", "message": "Failed", "color": "red"}' > badges/unit-tests.json

      - name: Code quality check
        run: |
          black --check --diff --color . | tee badges/black.txt || true
          PYTHONPATH=. pylint --fail-under=8.0 $(git ls-files '*.py') | tee badges/pylint.txt
          echo '{"label": "Code Quality", "message": "Passed", "color": "green"}' > badges/code-check.json
        continue-on-error: true

      - name: Record Code Quality Failure
        if: failure()
        run: |
          echo '{"label": "Code Quality", "message": "Failed", "color": "red"}' > badges/code-check.json

      - name: Security check
        run: |
          bandit -r . --exclude ./tests > badges/bandit.txt || true
          pip-audit | tee badges/security.txt
          echo '{"label": "Security Checks", "message": "Passed", "color": "green"}' > badges/security-check.json
        continue-on-error: true

      - name: Record Security Failure
        if: failure()
        run: |
          echo '{"label": "Security Checks", "message": "Failed", "color": "red"}' > badges/security-check.json

      - name: Upload Badge Data
        uses: actions/upload-artifact@v4
        with:
          name: badge-jsons
          path: badges/
